### PR TITLE
Fixed a crash in write_long_image (issue #13)

### LINKED ISSUE #13: Segfault when writing long_image
**Context:** 
- Ubuntu 20.04
- Tango 9.2.5a  (installed using the .deb packages) and 9.3.4 (local compilation)

**Problem:**
the following PyTango code generates a crash of TangoTest device:
```
import tango
tt = tango.DeviceProxy("sys/tg_test/1")
tt.long_image = tt.long_image_ro
```
The same "write request" works for any other data type and data format - e.g. ```tt.ulong_image = tt.ulong_image_ro``` works smoothly.

Crash was also reproduced under Octave and the TestDevice panel.

**Crash trace under gdb:**
```
Thread 10 "TangoTest" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fffedd51700 (LWP 215641)]
__memmove_avx_unaligned_erms () at ../sysdeps/x86_64/multiarch/memmove-vec-unaligned-erms.S:436
436	../sysdeps/x86_64/multiarch/memmove-vec-unaligned-erms.S: No such file or directory.
(gdb) backtrace 
#0  __memmove_avx_unaligned_erms () at ../sysdeps/x86_64/multiarch/memmove-vec-unaligned-erms.S:436
#1  0x000055555558455c in TangoTest_ns::TangoTest::write_long_image (this=0x55555564a6b0, attr=...) at TangoTest.cpp:2643
#2  0x00005555555a138e in TangoTest_ns::long_imageAttrib::write (this=0x555555647360, dev=0x55555564a6b0, att=...) at ./TangoTestClass.h:745
#3  0x00007ffff7c9331f in Tango::Device_3Impl::write_attributes_34(Tango::AttributeValueList const*, Tango::AttributeValueList_4 const*) ()
   from /lib/x86_64-linux-gnu/libtango.so.9
#4  0x00007ffff7c9a103 in Tango::Device_4Impl::write_attributes_4(Tango::AttributeValueList_4 const&, Tango::ClntIdent const&) () from /lib/x86_64-linux-gnu/libtango.so.9
#5  0x00007ffff74f2599 in omniCallHandle::upcall(omniServant*, omniCallDescriptor&) () from /lib/x86_64-linux-gnu/libomniORB4.so.2
#6  0x00007ffff7e6a0fb in Tango::_impl_Device_4::_dispatch(omniCallHandle&) () from /lib/x86_64-linux-gnu/libtango.so.9
#7  0x00007ffff7e6a5dd in Tango::_impl_Device_5::_dispatch(omniCallHandle&) () from /lib/x86_64-linux-gnu/libtango.so.9
#8  0x00007ffff74eba16 in omni::omniOrbPOA::dispatch(omniCallHandle&, omniLocalIdentity*) () from /lib/x86_64-linux-gnu/libomniORB4.so.2
#9  0x00007ffff74c99be in omniLocalIdentity::dispatch(omniCallHandle&) () from /lib/x86_64-linux-gnu/libomniORB4.so.2
#10 0x00007ffff750fa79 in omni::GIOP_S::handleRequest() () from /lib/x86_64-linux-gnu/libomniORB4.so.2
#11 0x00007ffff75100f0 in omni::GIOP_S::dispatcher() () from /lib/x86_64-linux-gnu/libomniORB4.so.2
#12 0x00007ffff750d65d in omni::giopWorker::execute() () from /lib/x86_64-linux-gnu/libomniORB4.so.2
#13 0x00007ffff74bd568 in omniAsyncWorker::real_run() () from /lib/x86_64-linux-gnu/libomniORB4.so.2
#14 0x00007ffff74be743 in omniAsyncPoolServer::workerRun(omniAsyncWorker*) () from /lib/x86_64-linux-gnu/libomniORB4.so.2
#15 0x00007ffff74bd0d1 in omniAsyncWorker::mid_run() () from /lib/x86_64-linux-gnu/libomniORB4.so.2
#16 0x00007ffff7e2a7b2 in Tango::create_PyPerThData(omni::omniInterceptors::createThread_T::info_T&) () from /lib/x86_64-linux-gnu/libtango.so.9
#17 0x00007ffff74be6b4 in omniAsyncWorker::run(void*) () from /lib/x86_64-linux-gnu/libomniORB4.so.2
#18 0x00007ffff73ed448 in omni_thread_wrapper () from /lib/x86_64-linux-gnu/libomnithread.so.4
#19 0x00007ffff73b4609 in start_thread (arg=<optimized out>) at pthread_create.c:477
#20 0x00007ffff6f8e293 in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
```

### PR DESCRIPTION
**Pull request by nleclercq**
TangoTest.write_long_image was using the "wrong" ptr to data. 
For consistency, also applied the same fix to other data type and format. 

Close #13

### CODE REVIEW

File: TangoTest.cpp [hunk 1]
```diff
@@ -1769,15 +1769,12 @@ void TangoTest::write_boolean_spectrum(Tango::WAttribute &attr)
...
-  const bool * p;
-  attr.get_write_value(p);
-
   long len = attr.get_write_value_length();
   DEBUG_STREAM << "Length :" << len << endl;
 
   len = (len <= kSpecLen) ? len : kSpecLen;
 
-  ::memcpy(attr_boolean_spectrum_read, p, len * sizeof(Tango::DevBoolean));
+  ::memcpy(attr_boolean_spectrum_read, w_val, len * sizeof(Tango::DevBoolean));
```
Comment (t-b) [inline TangoTest.cpp:1777]: Thanks for the PR. Can you clarify why `w_val` is correct and `p` not? Both were fetched via `attr.get_write_value`.

Comment (nleclercq) [reply TangoTest.cpp:1777]: The crash only occurred for the `long_image` attribute. It's a question of data size. The `long` type is 8 bytes long bits on x64 while Tango::DevLong is 4 bytes long on all plateforms. The `w_val` variable (who's part of the POGO generated code) is properly typed. A very old piece of code was overwriting 'w_val' 'using a ` long* p` variable to retrieve the write value. Because `p` is not of the expected type, it 's not properly set  by `attr.get_write_value` (i.e. `p` will be 0 is initialize to 0, undefined value otherwise). The crash used to occur during the call to `memcpy` where `p` was used as the source address (invalid pointer). 

For any other data type, the code has been modified for consistency reason.

Comment (t-b) [reply TangoTest.cpp:1777]: Got it. This makes sense now.

**Review by t-b — APPROVED** [review]

**Comment by t-b** [comment]
@bourtemb Not sure if we really need your review, but still I wanted to have you in the loop.

**Review by bourtemb — APPROVED** [review]
Thanks @nleclercq 
Looks good to me!

**Comment by nleclercq** [comment]
What's the next step of the PR procedure? Who does the actual merge?

**Comment by bourtemb** [comment]
> 
> 
> What's the next step of the PR procedure? Who does the actual merge?

Once it has been approved, anyone with appropriate permissions can do the merge. As a member of the cppTango Github team, you should be allowed to merge.
Usually I prefer to get the author of the PR doing the merge so he can choose his preferred way of doing the merge (rebase & merge, squash commits, merge commit...), depending on how relevant it is to keep separate commits or to squash them into 1 single commit.
Please be aware that the PR number will not appear in the history if you choose rebase & merge.
If you want, I can still do the merge.

We'll then have to tag a new version and make a new bug fix release on github.
A new TangoTest conda package (https://github.com/tango-controls/tango-conda-recipes/tree/master/tango-test) will have to be generated too and uploaded on tango-controls conda channel.

And if we want this fix to be in the next Tango Source Distribution version, we should inform this project to update the TangoTest version for the next release.
This can be done by commenting the issue announcing the preparation of a new release when there is one.
Today, there is one https://github.com/tango-controls/TangoSourceDistribution/issues/92

**Comment by nleclercq** [comment]
@bourtemb Squash commits/merge done. I let you do the rest of procedure. Thanks.
